# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe0626cfab6d1139d5551dc5d8e090a96423e179a2502f34ff0465456c5f4baeb5a8fab79e5cb09e35f86a314d9a7f3f3f07a63de22caf7b31d3aefb66b0626

test:
  secret_key_base: 23c1791ff348fdf73e0a02ef1fca467259c7a2b34bcb77e61a6b06c684929487c2580ed7c18b11da61f793af73487edc63c66fe235dec1e3bfd7d5b44b567d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
